import textstat

old = "This review of brain scans shows that there is evidence that the brain is growing extra extra extra brain mass at the level of the posterior frontal and anterior parietal lobes. This extra extra mass encases the falx and the adjacent superior sagittal sinus. There is no evidence that it is causing side effects such as brain damage or brain damage to the brain. However, there is some evidence to suggest that it might be associated to cancer of the brain and that it may be associated with lymphoma. Other less likely considerations include extra-axial dural based tumour based metastasis, lymphoma and less likely solitary fibrous tumor."

new = " This review identified 16 cc of MultiHance administered without complication without complication. The results of this review show a prominent bilobed paramedial extra-axial mass of 8 x 58 x 4.2 cm overlying the brain, with prominent dural thickening, especially extending posteriorly in the midline splaying the upper leaves of the falx through the level of the upper occipital lobe and occlusion of the adjacent superior sagittal sinus. The mass encases the right and especially left-sided paramedial addition to the brain. There is no evidence that there is significant change in white matter of the left and right frontal lobes, and a small amount also involving the right posterior frontal lobe. There are no signs that there has been any major brain damage. The nasal cavity appears unremarkable. The skull base of the skull is intact. The orbits are unremarkable . The paranasal sinuses demonstrate mucosal thickening partially outlining anterior and posterior ethmoid air cells and a hyperplastic polypoid component along the floor. The ventricles, sulci and basal cisterns appear unremarkable, although there is evidence to suggest that some ventricle blood vessels may be affected. The nasopharynx is symmetric. The brain shows evidence to have increased dural thickness, especially along its midline, but there is not enough evidence that it has changed significantly. The neurosurgeons suggest that there may have been a developmental abnormality within the left parietal lobe that may not be related to meningioma. Other less likely considerations include extra and subcortical metastasis, lymphoma and less likely solitary fibrous tumor."


print(textstat.flesch_kincaid_grade(old))
print(textstat.flesch_kincaid_grade(new))
